import { useState } from "react";
import useAuth from "./useAuth";

export function AdminBookingInsert() {
    const { token, user,error, setToken, setUser, setError } = useAuth();
    const [date, setDate] = useState('');
    const [timeStart, setTimeStart] = useState('');
    const [timeEnd, setTimeEnd] = useState('');
    //I have to change the bookinData to the correct format
    //generated by ai
    async function insertBooking(e: any) {
        e.preventDefault();
        const bookingData = {
            date: date,
            timeStart: timeStart,
            timeEnd: timeEnd,
        }
        const response = await fetch('http://localhost:3000/booking', {
            method: 'POST',
            headers: {
                'Content-type': 'application/json',
                'Accept': 'application/json',
                'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify(bookingData),
        });
        if (!response.ok) {
            const errorObj = await response.json();
            console.log(errorObj);
            return;
        }
        const bookingObj = await response.json();
        console.log(bookingObj);
    }

    return (
        <>
        <div className="container login">
        <h1>Időintervallum feltöltése</h1>
        <form>
            <div className="form-group">
                <label htmlFor="date">Dátum:</label>
                <input type="date" className="form-control" id="date" onChange={e => {setDate(e.currentTarget.value)}} />
            </div>
            <div className="form-group">
                <label htmlFor="timeStart">Idő kezdete:</label>
                <input type="time" className="form-control" id="timeStart" onChange={e => {setTimeStart(e.currentTarget.value)}} />
                <label htmlFor="timeEnd">Idő vége:</label>
                <input type="time" className="form-control" id="timeEnd" onChange={e => {setTimeEnd(e.currentTarget.value)}}/>

            </div>
            <button type="submit" className="btn btn-primary">Feltöltés</button>
        </form>
        </div>
        </>
    )
}