import { useEffect, useState } from "react";
import useAuth from "./useAuth";

export function AdminBookingNotReserved() {
    const { token, user,error, setToken, setUser, setError } = useAuth();
    const [bookingData, setBookingData] = useState([]);
    //I have to change the bookinData to the correct format
    //generated by ai   
   
    useEffect(() => {
        console.log('user: ', user);
        async function getAllNotReserved() {
            console.log('token: ', token);
             const response = await fetch(`http://localhost:3000/booking/not_reserved/}`, {
                 method: 'GET',
                 headers: {
                     'Content-type': 'application/json',
                     'Accept': 'application/json',
                     'Authorization': `Bearer ${token}`
                 },
             });
             if (!response.ok) {
                 const errorObj = await response.json();
                 console.log(errorObj);
                 return;
             }
             console.log('response: ', response);
             const data = await response.json();
            await setBookingData(data);
         }

        getAllNotReserved();
    }, [bookingData] || [user] || [token] || []);

    return (
        <>
        <div className="container login">
        <h1>Szabad időpontok kezelése</h1>
        {
            bookingData.map((booking: any) => {
                return (
                    <div key={booking.id}>
                        <p>{booking.name} - {booking.dateStart} - {booking.dateEnd}</p>
                    </div>
                )
            })
        }
        </div>
        </>
    )
}