import { useState } from "react";
import useAuth from "./useAuth";

export function AdminBookingInsert() {
    const { token, user,error, setToken, setUser, setError } = useAuth(true);
    const [date, setDate] = useState(new Date());
    const [timeStart, setTimeStart] = useState('');
    const [timeEnd, setTimeEnd] = useState('');
    //I have to change the bookinData to the correct format
    //generated by ai   
    async function insertBooking(e: any) {
        e.preventDefault();
        const startDate = new Date(date);
        const endDate = new Date(date);
        const start = timeStart.split(':');
        const end = timeEnd.split(':');
        startDate.setHours(parseInt(start[0]) + 2, parseInt(start[1]), 0);      //somehow the hours are not correct, so I have to add 1 to the hours
        endDate.setHours(parseInt(end[0]) + 2, parseInt(end[1]), 0);
        if (startDate >= endDate) {
            console.log('A kezdő időpontnak korábbinak kell lennie, mint a befejező időpont!');
            return;
        }
        const toSendStart = startDate.toISOString();
        const toSendEnd = endDate.toISOString();
        console.log('Start: ', toSendStart);
        console.log('End: ', toSendEnd);


        const bookingData = {
            admin: user!.admin,
            name: user!.name,
           dateStart: toSendStart,
            dateEnd: toSendEnd,
            extra: false,
            type: '',
        }
        if(!user || !user.name || typeof user.name !== 'string'){
            bookingData.name = '';
        }
        console.log('user: ', user)
        console.log(bookingData)
        const response = await fetch('http://localhost:3000/booking', {
            method: 'POST',
            headers: {
                'Content-type': 'application/json',
                'Accept': 'application/json',
                'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify(bookingData),
        });
        if (!response.ok) {
            const errorObj = await response.json();
            console.log(errorObj);
            return;
        }

    }

    return (
        <>
        <div className="container login">
        <h1>Időintervallum feltöltése</h1>
        <form>
            <div className="form-group">
                <label htmlFor="date">Dátum:</label>
                <input type="date" className="form-control" id="date" onChange={e => {setDate(new Date(e.currentTarget.value))}} />
            </div>
            <div className="form-group">
                <label htmlFor="timeStart">Idő kezdete:</label>
                <input type="time" className="form-control" id="timeStart" onChange={e => {setTimeStart(e.currentTarget.value)}} />
                <label htmlFor="timeEnd">Idő vége:</label>
                <input type="time" className="form-control" id="timeEnd" onChange={e => {setTimeEnd(e.currentTarget.value)}}/>

            </div>
            <button type="submit" className="btn btn-primary" onClick={insertBooking}>Feltöltés</button>
        </form>
        </div>
        </>
    )
}